const abreviaturas = {
    "Este": "E",
    "Norte": "Nte.",
    "Noreste": "NE",
    "Noroeste": "NO",
    "Oeste": "O",
    "Oriente": "Ote.",
    "Sur": "S",
    "Sureste": "SE",
    "Suroeste": "SO",
    "Poniente": "Pte.",
    "1ra. ": "1ª",
    "Primero": "1º",
    "Primera": "1ª",
    "Primer": "1er",
    "2da. ": "2ª ",
    "Segunda": "2ª",
    "Segundo": "2º",
    "3ra. ": "3ª ",
    "Tercera": "3ª",
    "Tercero": "3º",
    "4ta. ": "4ª ",
    "Cuarta": "4ª",
    "Cuarto": "4º",
    "5ta. ": "5ª ",
    "Quinta": "5ª",
    "Quinto": "5º",
    "6ta. ": "6ª ",
    "Sexta": "6ª",
    "Sexto": "6º",
    "7ma. ": "7ª ",
    "Séptima": "7ª",
    "Séptimo": "7º",
    "8va. ": "8ª ",
    "Octava": "8ª",
    "Octavo": "8º",
    "9na. ": "9ª ",
    "Novena": "9ª",
    "Noveno": "9º",
    "10ma. ": "10ª ",
    "Décima": "10ª",
    "Décimo": "10º",
    "11va. ": "11ª ",
    "Undécima": "11ª",
    "Undécimo": "11º",
    "12va. ": "12ª ",
    "Duodécima": "12ª",
    "Duodécimo": "12º",
    "13ra. ": "13ª ",
    "Decimotercera": "13ª",
    "Decimotercero": "13º",
    "14ta. ": "14ª ",
    "Decimocuarta": "14ª",
    "Decimocuarto": "14º",
    "15ta. ": "15ª ",
    "Decimoquinta": "15ª",
    "Decimoquinto": "15º",
    "16ta. ": "16ª ",
    "Decimosexta": "16ª",
    "Decimosexto": "16º",
    "17ma. ": "17ª ",
    "Decimoséptima": "17ª",
    "Decimoséptimo": "17º",
    "18va. ": "18ª ",
    "Decimoctava": "18ª",
    "Decimoctavo": "18º",
    "19na. ": "19ª ",
    "Decimonovena": "19ª",
    "Decimonoveno": "19º",
    "20va. ": "20ª ",
    "Vigésima": "20ª",
    "Vigésimo": "20º",
    "21ra. ": "21ª ",
    "Vigésima primera": "21ª",
    "Vigésimo primero": "21º",
    "22da. ": "22ª ",
    "Vigésima segunda": "22ª",
    "Vigésimo segundo": "22º",
    "23ra. ": "23ª ",
    "Vigésima tercera": "23ª",
    "Vigésimo tercero": "23º",
    "24ta. ": "24ª ",
    "Vigésima cuarta": "24ª",
    "Vigésimo cuarto": "24º",
    "25ta. ": "25ª ",
    "Vigésima quinta": "25ª",
    "Vigésimo quinto": "25º",
    "26ta. ": "26ª ",
    "Vigésima sexta": "26ª",
    "Vigésimo sexto": "26º",
    "27ma. ": "27ª ",
    "Vigésima séptima": "27ª",
    "Vigésimo séptimo": "27º",
    "28va. ": "28ª ",
    "Vigésima octava": "28ª",
    "Vigésimo octavo": "28º",
    "29na. ": "29ª ",
    "Vigésima novena": "29ª",
    "Vigésimo noveno": "29º",
    "30ta. ": "30ª ",
    "Trigésima": "30ª",
    "Trigésimo": "30º",
    "31ra. ": "31ª ",
    "Trigésima primera": "31ª",
    "Trigésimo primero": "31º",
    "32da. ": "32ª ",
    "Trigésima segunda": "32ª",
    "Trigésimo segundo": "32º",
    "33ra. ": "33ª ",
    "Trigésima tercera": "33ª",
    "Trigésimo tercero": "33º",
    "34ta. ": "34ª ",
    "Trigésima cuarta": "34ª",
    "Trigésimo cuarto": "34º",
    "35ta. ": "35ª ",
    "Trigésima quinta": "35ª",
    "Trigésimo quinto": "35º",
    "36ta. ": "36ª ",
    "Trigésima sexta": "36ª",
    "Trigésimo sexto": "36º",
    "37ma. ": "37ª ",
    "Trigésima séptima": "37ª",
    "Trigésimo séptimo": "37º",
    "38va. ": "38ª ",
    "Trigésima octava": "38ª",
    "Trigésimo octavo": "38º",
    "39na. ": "39ª ",
    "Trigésima novena": "39ª",
    "Trigésimo noveno": "39º",
    "40ta. ": "40ª ",
    "Cuadragésima": "40ª",
    "Cuadragésimo": "40º",
    "41ra. ": "41ª ",
    "Cuadragésima primera": "41ª",
    "Cuadragésimo primero": "41º",
    "42da. ": "42ª ",
    "Cuadragésima segunda": "42ª",
    "Cuadragésimo segundo": "42º",
    "43ra. ": "43ª ",
    "Cuadragésima tercera": "43ª",
    "Cuadragésimo tercero": "43º",
    "44ta. ": "44ª ",
    "Cuadragésima cuarta": "44ª",
    "Cuadragésimo cuarto": "44º",
    "45ta. ": "45ª ",
    "Cuadragésima quinta": "45ª",
    "Cuadragésimo quinto": "45º",
    "46ta. ": "46ª ",
    "Cuadragésima sexta": "46ª",
    "Cuadragésimo sexto": "46º",
    "47ma. ": "47ª ",
    "Cuadragésima séptima": "47ª",
    "Cuadragésimo séptimo": "47º",
    "48va. ": "48ª ",
    "Cuadragésima octava": "48ª",
    "Cuadragésimo octavo": "48º",
    "49na. ": "49ª ",
    "Cuadragésima novena": "49ª",
    "Cuadragésimo noveno": "49º",
    "50ta. ": "50ª ",
    "Quincuagésima": "50ª",
    "Quincuagésimo": "50º",
    "Almacén": "Alm.",
    "Arquitecto": "Arq.",
    "Arzobispo": "Arz.",
    "Autopista": "Autop.",
    "Avenida": "Av.",
    "Ayuntamiento": "Ayto.",
    "Bulevar": "Blvd.",
    "Calle": "Cl.",
    "Callejón": "Cjn.",
    "Calzada": "Calz.",
    "Camino": "Cam.",
    "Capitán": "Cap.",
    "Carretera": "Carrt.",
    "Centro Comercial": "C.C.",
    "Cerrada": "Cda.",
    "Circuito": "Circ.",
    "Código": "Cód.",
    "Comandante": "Cmte.",
    "Combate": "Cbte.",
    "Consultorio": "Consult.",
    "Continuación": "Cont.",
    "Coronel": "Cnel.",
    "Departamento": "Depto.",
    "Diagonal": "Diag.",
    "Distrito": "Dtto.",
    "Doctor": "Dr.",
    "Doctora": "Dra.",
    "Don": "Dn.",
    "Doña": "Dña.",
    "Edificio": "Edif.",
    "Entrada": "Ent.",
    "Entronque Carretero": "E.C.",
    "Esquina": "Esq.",
    "Estación de Servicio": "ES",
    "Estado": "Edo.",
    "Extensión": "Ext.",
    "Fábrica": "Fáb.",
    "General": "Gral.",
    "Glorieta": "Gta.",
    "Gobernador": "Gob.",
    "Gobernadora": "Gdora.",
    "Fábrica": "Fáb.",
    "Laboratorio": "Lab.",
    "Hermana": "Hna.",
    "Hermanas": "Hnas.",
    "Hermano": "Hno.",
    "Hermanos": "Hnos.",
    "Ingeniero": "Ing.",
    "Intendente": "Int.",
    "Interior": "Intr.",
    "Kilómetro": "Km",
    "Licenciado": "Lic.",
    "Local": "Loc.",
    "Lote": "Lt.",
    "Manzana": "Manz.",
    "México": "MEX",
    "Monseñor": "Mons.",
    "Obispo": "Ob.",
    "Oficina": "Of.",
    "Pasaje": "Pje.",
    "Plaza": "Pza.",
    "Pontífice": "Pnt.",
    "Presbítero": "Presb.",
    "Presidente": "Pdte.",
    "Privada": "Priv.",
    "Profesor": "Prof.",
    "Profesora": "Profa.",
    "República": "Rep.",
    "Reverenda": "Rvda.",
    "Reverendo": "Rvd.",
    "Santa": "Sta.",
    "Santo": "Sto.",
    "Sargento": "Sgto.",
    "Sección": "Secc.",
    "Sociedad": "Sdad.",
    "Sociedad": "Soc.",
    "Teniente": "Tte.",
    "Universidad": "Univ.",
    "Prolongación": "Prol.",
};