const renombrar = {
    // Nombres propios
    "andres": "Andrés",
    "jose": "José",
    "maria": "María",
    "jesus": "Jesús",
    "gabriel": "Gabriel",
    "miguel": "Miguel",
    "francisco": "Francisco",
    "carlos": "Carlos",
    "belen": "Belén",
    "mateos": "Mateos",
    "martin": "Martín",
    "raul": "Raúl",
    "ramon": "Ramón",
    "alex": "Álex",
    "juan": "Juan",
    "diego": "Diego",

    // Apellidos
    "perez": "Pérez",
    "lopez": "López",
    "gomez": "Gómez",
    "gonzalez": "González",
    "rodriguez": "Rodríguez",
    "martinez": "Martínez",
    "hernandez": "Hernández",
    "garcia": "García",
    "sanchez": "Sánchez",
    "diaz": "Díaz",
    "ruiz": "Ruiz",
    "torres": "Torres",

    // Países/ciudades
    "mexico": "México",
    "peru": "Perú",
    "panama": "Panamá",
    "argentina": "Argentina",
    "espana": "España",
    "colombia": "Colombia",
    "chile": "Chile",
    "bogota": "Bogotá",
    "lima": "Lima",
    "buenos aires": "Buenos Aires",
    "madrid": "Madrid",
    "barcelona": "Barcelona",
    "caracas": "Caracas",

    // Palabras comunes mal escritas
    "heroes": "Héroes",
    "direccion": "Dirección",
    "telefono": "Teléfono",
    "correo": "Correo",
    "fecha": "Fecha",
    "año": "Año",
    "exito": "Éxito",
    "musica": "Música",
    "television": "Televisión",
    "informacion": "Información",
    "acion": "Acción",
    "ejemplo": "Ejemplo",
    "cancion": "Canción",
    "imagen": "Imagen",
    "publico": "Público",
    "unico": "Único",
    "facil": "Fácil",
    "dificil": "Difícil",
    "util": "Útil",
    "caracter": "Carácter",
    "sintesis": "Síntesis",
    "etica": "Ética"
};